title: Nikil Kumar 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2>Data Scientist</h2>
  <br>
  <h4> Experience : Intern @ Innodatatics,
  Bengaluru.
  (DEC 2019 â€“ FEB 2020)</h4> 
  <br>
  <br>
  <a href="mailto:nikil.kumar.1121@gmail.com">email</a> 
  <br>
  <br>
  <a href="tel:8328554859">Mobile no</a>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/nikil-kumar-337941132/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
